### ISSUE TITLE
The recent version of Popup Blocker (strict) 0.3.5 causes problems in webs

### ISSUE THREAD

**Issue by Makrod** [schomery/popup-blocker#45]
The recent version of Popup Blocker (strict) 0.3.5 is causing many problems in the webs, many of them are shown in white as outlook.live.com being impossible to access to see the mails without deactivating before the plugin, in the online translators As bing.com does not work either, in the page of banggood.com is also giving problems.

The whitelist is not working in the plugin either, it needs the complete deactivation so that everything works correctly.

Before version 0.3.5 its operation was good now it gives a lot of problems.

Anyone know what happened?

Thanks.

**Comment by nekq** [comment]
I'm having the same problem. Random websites simply show a few html tags in their text only form.
The bugs appeared today and I have version 0.5.3.
Seems to be random cause outlook.live.com is working fine for me.

**Comment by Makrod** [comment]
I leave some images of my problem I'm sure the problem has been of the update 0.3.5 today.

outlook.live.com

https://postimg.org/image/av37zjz33/

banggood.com

https://postimg.org/image/h2sfylnkv/

If I disable the plugin completely everything works correctly add the web pages to the white list does not work.

**Comment by schomery** [comment]
please do a right-click and open "inspect" window on one of these pages. switch to the console tab and refresh the page. do you get any error in the console?

Do you have any option changes  from the defaults?

**Comment by schomery** [comment]
@narcolepticinsomniac can you reproduce?

**Comment by narcolepticinsomniac** [comment]
Nope. Both sites work fine in Chromium, and FF is still on 0.3.4 so they've gotta be using Chrome, right?

**Comment by schomery** [comment]
Yes. Based on the images I would say it is Chrome.

**Comment by schomery** [comment]
https://chrome.google.com/webstore/detail/popup-blocker-strict/aefkmifgmaafnojlojpnekbpbmjiiogg/reviews

**Comment by narcolepticinsomniac** [comment]
Yeah, based on the mention of adblock I tried disabling it, and can repro on banggood.com without it.

**Comment by schomery** [comment]
so when there is no adblock this banggood.com is not loading for you?

**Comment by narcolepticinsomniac** [comment]
Correct. No adblock but PBS = the above pic.

**Comment by schomery** [comment]
Please confirm the fix on the latest dev.

**Comment by narcolepticinsomniac** [comment]
Confirmed.

**Comment by schomery** [comment]
Thanks @narcolepticinsomniac! @Makrod and @nekq version 0.3.6 should have fixed the bug. If you are still experiencing it, please provide more examples.

**Comment by Makrod** [comment]
Confirm version 0.3.6 fixes all problems.

Thank you.

**Comment by Anaerin** [comment]
This is NOT fixed. Using FireFox 57.0a1 (latest nightly), 0.3.6 of Popup Blocker, and the site https://www.polymer-project.org/2.0/docs/browsers (for example) or YouTube's "New" interface, gives the console error "TypeError: Polymer.DomModule.import is not a function" and displays nothing.

**Comment by Myer** [comment]
@Anaerin: You are talking about another issue: #53 
It has been fixed already but not yet been released.
